sudo: false

branches:
  only:
    - 7.0

addons:
  apt:
    packages:
      - doxygen

script:
  - git submodule update --init --reference ./
  - doxygen Doxygen.epics

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: 7.0
    